language: emacs-lisp

env:
  matrix:
    - EMACS=emacs23           TARGET=check
    - EMACS=emacs24           TARGET=check
    - EMACS=emacs-snapshot    TARGET=check
    - EMACS=emacs24           TARGET=deploy-manual
  global:
    - secure: "ejv1+ub/v+Hm/23fhp4zLAHT3HiCG+YdDHai57LDe4LfEZCeGz4i/6LazbPbwm58v2YuKvMcdNshebc1s4A293ARJryPyFfW/8kEe+3hQ+cDxunNdHfqcS8SyhcDG0mrv7dqiVAtMJqB8qZb0c161KeEM8nyhC0wyQ+EZ5qJnzM="

matrix:
  allow_failures:
    - env:
        - EMACS=emacs-snapshot

install:
  - if [ "$EMACS" = "emacs23" ]; then
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs23-gtk emacs23-el;
    fi
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi
  - if [ "$EMACS" = "emacs-snapshot" ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs-snapshot &&
        sudo apt-get install -qq emacs-snapshot-el;
    fi
  - if [ "$TARGET" = "deploy-manual" ]; then
        curl -O http://ftp.gnu.org/gnu/texinfo/texinfo-5.2.tar.xz;
        tar -xf texinfo-5.2.tar.xz;
        cd texinfo-5.2;
        ./configure;
        make;
        sudo make install;
        cd ..;
    fi

script:
  lsb_release -a && $EMACS --version && make EMACS=$EMACS $TARGET

notifications:
  email: false

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
