#!/bin/sh

. $HOME/.shenv

# mark all sent mail as read
notmuch tag -unread -- folder:sent

# mark all drafts as drafts, and as read
notmuch tag -unread +draft -- folder:drafts

# mark all spam as spam
notmuch tag +spam -- folder:spam

# mark all trash as trash
notmuch tag +deleted -- folder:trash

# mark all archived mail as read and unflagged
notmuch tag -unread -flagged -- path:pre2012/** or path:2013/** or path:2014/** or path:2015/** or path:2016/** or path:2017a/**
